robot_base_frame: base_link

transform_tolerance: 0.5

footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]

inflation:
    footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
    inflation_radius: 0.7

obstacles:
  observation_sources: scan_filtered
  scan_filtered:
    data_type: LaserScan
    topic: scan_filtered
    marking: true
    clearing: true
    obstacle_range: 4.0
    raytrace_range: 5.0
    min_obstacle_height: 0.20
    max_obstacle_height: 0.30
  z_voxels: 16
  z_resolution: 0.125
  max_obstacle_height: 2.0
